In [8]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC

In [2]:
df = pd.read_csv('svm-data.csv', names=['y', 'x1', 'x2'])

In [3]:
df

y    x1    x2
0  0  0.70  0.29
1  1  0.23  0.55
2  0  0.72  0.42
3  0  0.98  0.68
4  0  0.48  0.39
5  1  0.34  0.73
6  0  0.44  0.06
7  1  0.40  0.74
8  0  0.18  0.18
9  1  0.53  0.53

In [6]:
x = df.drop('y', axis=1)

In [9]:
y = np.ravel(df.y)

In [4]:
svm = SVC(random_state=241, C=100000, kernel='linear')

In [11]:
svm.fit(x, y)

SVC(C=100000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=241, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
svm.support_

array([3, 4, 9], dtype=int32)

In [13]:
svm.support_vectors_

array([[ 0.98,  0.68],
       [ 0.48,  0.39],
       [ 0.53,  0.53]])

In [16]:
svm.support_ + 1

array([ 4,  5, 10], dtype=int32)